# Generated by Django 2.2.1 on 2019-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=200)),
                ('pub', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
